.github/.codecov.yml, .github/workflows/ci.yml, .github/workflows/coverage.yml, .github/workflows/post-merge.yml, .github/workflows/verify-deps.yml, commitlint.config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/1)
=> Initial commit

Cargo.toml, crates/gateway/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/2)
=> Add cargo.toml to mempool

crates/gateway/src/errors.rs, crates/gateway/src/lib.rs, crates/gateway/src/starknet_api_test_utils.rs, crates/gateway/src/transaction_validator.rs, crates/gateway/src/transaction_validator_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/22)
=> feat: add stateless validator skelaton

Cargo.toml, crates/gateway/src/starknet_api_test_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/31)
=> chore: update to latest external tx format

Cargo.lock, Cargo.toml, crates/mempool_node/Cargo.toml, crates/mempool_node/src/main.rs
=> build: add mempool node crate

commitlint.config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/36)
=> ci: add scopes for commitlint configuration

crates/gateway/src/lib.rs, crates/gateway/src/stateless_transaction_validator.rs, crates/gateway/src/stateless_transaction_validator_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/40)
=> feat: rename file to stateless transaction validator

crates/gateway/src/gateway.rs
Fields are pub
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/52)
=> chore(gateway): remove unnecessary ctor

Cargo.lock, Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/60)
=> chore: upgrade sn-api commit

crates/gateway/src/errors.rs, crates/gateway/src/starknet_api_test_utils.rs, crates/gateway/src/stateless_transaction_validator.rs, crates/gateway/src/stateless_transaction_validator_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/53)
=> feat: stateless validator add signature len validator

crates/gateway/src/starknet_api_test_utils.rs, crates/gateway/src/stateless_transaction_validator_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/61)
=> test: organize tests for maintainability

crates/gateway/src/config.rs, crates/gateway/src/config_test.rs, crates/gateway/src/gateway.rs, crates/gateway/src/json_files_for_testing/gateway_config.json, crates/gateway/src/lib.rs, crates/mempool_node/src/config/config_test.rs, crates/mempool_node/src/config/mod.rs, crates/mempool_node/src/test_files/mempool_node_config.json
=> fix: duplicate config

Cargo.lock, Cargo.toml, crates/gateway/Cargo.toml, crates/gateway/src/errors.rs, crates/gateway/src/lib.rs, crates/gateway/src/stateful_transaction_validator.rs, crates/gateway/src/utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/42)
=> feat: add stateful validations

crates/gateway/src/errors.rs, crates/gateway/src/gateway.rs, crates/gateway/src/gateway_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/70)
=> feat: add gateway response to gateway result

Cargo.lock, crates/mempool_infra/Cargo.toml, crates/mempool_infra/src/component_runner.rs, crates/mempool_infra/src/lib.rs
=> feat: add component runner

Cargo.lock, Cargo.toml, crates/gateway/Cargo.toml, crates/gateway/src/lib.rs, crates/gateway/src/rpc_objects.rs, crates/gateway/src/rpc_state_reader.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/64)
=> feat: rpc state reader

Cargo.lock, Cargo.toml, crates/gateway/Cargo.toml, crates/gateway/src/errors.rs, crates/gateway/src/gateway.rs, crates/mempool_node/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/87)
=> feat: remove obsulete code in gateway

crates/gateway/src/gateway.rs, crates/gateway/src/gateway_test.rs, crates/gateway/src/stateless_transaction_validator.rs, crates/gateway/tests/routing_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/71)
=> feat: stateless validations in add transaction

crates/gateway/src/rpc_objects.rs, crates/gateway/src/rpc_state_reader.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/81)
=> feat: add get_storage_at to rpc_state_reader

Cargo.lock, Cargo.toml, crates/gateway/src/stateless_transaction_validator.rs, crates/mempool/src/errors.rs, crates/mempool/src/mempool.rs, crates/mempool/src/mempool_test.rs, crates/mempool/src/priority_queue.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/47)
=> feat: implement add_tx in mempool struct

Cargo.lock, crates/mempool_infra/Cargo.toml, crates/mempool_infra/src/component_runner.rs, crates/mempool_infra/src/component_runner_test.rs, crates/mempool_infra/src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/99)
=> feat: changing component runner and adding tests

crates/gateway/src/rpc_objects.rs, crates/gateway/src/rpc_state_reader.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/96)
=> feat: add get_block_info to rpc reader

crates/gateway/src/errors.rs, crates/gateway/src/rpc_objects.rs, crates/gateway/src/rpc_state_reader.rs, crates/gateway/src/stateful_transaction_validator.rs, crates/gateway/src/stateful_transaction_validator_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/102)
=> feat: add state reader creation and block info read to stateful validations

crates/mempool_infra/src/channels_test.rs, crates/mempool_infra/src/lib.rs
commit-id:4ad09326
---
**Stack**:
- #109
- #108 ⬅
=> feat: add new channel-based invocation

crates/gateway/src/rpc_state_reader.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/107)
=> chore: improve rpc_state_reader error handling

crates/gateway/tests/end_to_end_test.rs, crates/mempool_types/src/mempool_types.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/98)
=> test: add simple test that communicates through network component

crates/gateway/tests/end_to_end_test.rs, crates/mempool/src/mempool_test.rs, crates/mempool_types/src/mempool_types.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/118)
=> style: use to instead of 2 for network types and vars

crates/gateway/src/starknet_api_test_utils.rs, crates/gateway/tests/end_to_end_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/120)
=> refactor: move create_internal_tx_for_testing to utils

crates/gateway/src/config_test.rs, crates/gateway/src/json_files_for_testing/gateway_network_config.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/111)
=> test: add test fix infra for gateway network connection config

crates/gateway/src/gateway.rs, crates/gateway/src/gateway_test.rs, crates/gateway/tests/routing_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/121)
=> refactor: move app function to gateway method

crates/mempool/src/mempool.rs, crates/mempool/src/mempool_test.rs, crates/mempool/src/priority_queue.rs, crates/mempool_types/src/lib.rs, crates/mempool_types/src/mempool_types.rs, crates/mempool_types/src/utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/103)
=> refactor: add thin transaction and implement in mempool

Cargo.lock, Cargo.toml, crates/gateway/Cargo.toml, crates/gateway/src/rpc_objects.rs, crates/gateway/src/rpc_state_reader.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/124)
=> feat: add get_comlied_contract_class to rpc_state_reader

crates/gateway/src/config_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/113)
=> test: generazlie test_valid_config test util

crates/gateway/src/gateway.rs, crates/gateway/src/gateway_test.rs, crates/gateway/tests/routing_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/123)
=> feat: add network to gateway app method

crates/gateway/src/config.rs, crates/gateway/src/config_test.rs, crates/gateway/src/gateway.rs, crates/gateway/src/gateway_test.rs, crates/gateway/src/json_files_for_testing/stateless_transaction_validator_config.json, crates/gateway/src/stateless_transaction_validator.rs, crates/gateway/tests/routing_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/126)
=> feat: serialize config for stateless transaction validator config

Cargo.lock, Cargo.toml, crates/gateway/src/gateway.rs, crates/gateway/src/lib.rs, crates/gateway/src/rpc_state_reader.rs, crates/gateway/src/state_reader.rs, crates/gateway/src/state_reader_test_utils.rs, crates/gateway/src/stateful_transaction_validator.rs, crates/gateway/src/stateful_transaction_validator_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/122)
=> feat: state reader factory

crates/gateway/src/rpc_state_reader.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/129)
=> chore: change url type url to string in rpc state reader config

crates/gateway/src/gateway.rs, crates/gateway/src/gateway_test.rs, crates/gateway/tests/end_to_end_test.rs, crates/gateway/tests/routing_test.rs, crates/mempool_types/src/mempool_types.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/140)
=> refactor: rename transaction term

crates/gateway/src/config.rs, crates/gateway/src/config_test.rs, crates/gateway/src/json_files_for_testing/rpc_state_reader_config.json, crates/gateway/src/rpc_state_reader.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/130)
=> feat: add serialize for rpc_state_reader_config

crates/gateway/Cargo.toml, crates/gateway/src/config.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/141)
=> chore: mark rpc state reader config create for testing for cfg

Cargo.lock, Cargo.toml, crates/gateway/tests/end_to_end_test.rs, crates/mempool/Cargo.toml, crates/mempool/src/mempool.rs, crates/mempool_types/src/mempool_types.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/119)
=> feat: listen for requests from a network for the mempool

crates/mempool_infra/src/component_server.rs, crates/mempool_infra/src/component_server_client_test.rs
=> feat: make executable operable on mutable references

crates/gateway/src/errors.rs, crates/gateway/src/gateway.rs, crates/gateway/src/gateway_test.rs, crates/gateway/tests/end_to_end_test.rs, crates/gateway/tests/routing_test.rs, crates/mempool/src/mempool.rs, crates/mempool_types/src/mempool_types.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/133)
=> feat: send add tx requests through network channel

Cargo.lock, crates/mempool/src/mempool.rs, crates/mempool/src/mempool_test.rs, crates/mempool_types/Cargo.toml, crates/mempool_types/src/mempool_types.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/153)
=> feat: connect batcher network channels

crates/gateway/src/gateway.rs, crates/gateway/src/gateway_test.rs, crates/gateway/src/lib.rs, crates/gateway/src/rpc_state_reader.rs, crates/gateway/src/state_reader.rs, crates/gateway/src/state_reader_test_utils.rs, crates/gateway/src/stateful_transaction_validator.rs, crates/gateway/tests/end_to_end_test.rs, crates/gateway/tests/routing_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/139)
=> feat: add state_reader_factory to Gateway and AppState

crates/gateway/src/stateful_transaction_validator.rs, crates/gateway/src/stateful_transaction_validator_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/142)
=> chore: change the type of chain info member of stateful transaction validator

crates/gateway/src/config.rs, crates/gateway/src/gateway.rs, crates/gateway/src/gateway_test.rs, crates/gateway/src/stateful_transaction_validator.rs, crates/gateway/src/stateful_transaction_validator_test.rs, crates/gateway/tests/end_to_end_test.rs, crates/gateway/tests/routing_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/144)
=> chore: move the stateful transaction validator config into config file

crates/gateway/src/starknet_api_test_utils.rs, crates/gateway/src/utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/162)
=> chore: refactor the use of tip and nonce ref getters

config/default_config.json, crates/mempool_node/src/bin/dump_config.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/128)
=> feat: adding ability to dump default configuration

crates/gateway/src/utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/163)
=> chore: use ref getters from starknet api

crates/gateway/src/gateway.rs, crates/gateway/src/stateful_transaction_validator.rs, crates/gateway/src/stateful_transaction_validator_test.rs, crates/gateway/src/utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/152)
=> chore: return tx hash

crates/mempool/src/mempool.rs, crates/mempool_types/src/mempool_types.rs
commit-id:0b49a012
---
**Stack**:
- #167
- #166
- #161
- #160
- #159 ⬅
=> refactor: move mempool result to mempool types

crates/gateway/src/config.rs, crates/mempool_node/src/config/config_test.rs, crates/mempool_node/src/config/mod.rs, crates/mempool_node/src/test_files/mempool_node_config.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/155)
=> feat: use gateway config in mempool config

crates/gateway/src/gateway.rs, crates/gateway/tests/end_to_end_test.rs, crates/gateway/tests/routing_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/138)
=> feat: use gateway config in the gateway

crates/gateway/src/config.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/132)
=> feat: create serialize config for stateful transaction validator

crates/gateway/src/gateway.rs, crates/gateway/src/utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/168)
=> chore: store transaction_hash in ThinTransaction

crates/gateway/src/gateway_test.rs, crates/gateway/src/starknet_api_test_utils.rs, crates/gateway/src/stateful_transaction_validator_test.rs, crates/gateway/src/stateless_transaction_validator_test.rs, crates/gateway/tests/end_to_end_test.rs, crates/gateway/tests/routing_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/131)
=> refactor: replace invoke json file with macro creation

Cargo.lock, crates/gateway/Cargo.toml, crates/gateway/src/errors.rs, crates/gateway/src/gateway_client.rs, crates/gateway/src/lib.rs, crates/gateway/tests/end_to_end_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/143)
=> feat: implement gateway client

crates/gateway/src/starknet_api_test_utils.rs, crates/gateway/src/stateful_transaction_validator_test.rs, crates/gateway/src/utils.rs, crates/mempool/src/mempool.rs, crates/mempool/src/mempool_test.rs, crates/mempool/src/priority_queue.rs, crates/mempool_types/src/mempool_types.rs, crates/mempool_types/src/utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/78)
=> fix: minor changes in priority queue

crates/gateway/src/gateway.rs, crates/gateway/tests/end_to_end_test.rs, crates/gateway/tests/routing_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/170)
=> chore: add app_state as a member of the Gateway

crates/gateway/tests/end_to_end_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/157)
=> refactor: cosmitic changes for end-to-end test

crates/gateway/src/gateway_test.rs, crates/gateway/src/starknet_api_test_utils.rs
Move negative and positive flows to be in case parameters.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/135)
=> refactor: gateway test

crates/gateway/src/starknet_api_test_utils.rs, crates/mempool/src/mempool_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/191)
=> chore: remove internal transaction utils

crates/gateway/src/starknet_api_test_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/182)
=> feat: create a macro for declare tx

crates/mempool_infra/src/component_client_rpc.rs, crates/mempool_infra/src/component_server_client_rpc_test.rs, crates/mempool_infra/src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/190)
=> test: add empty test for client/server rpc implementation

crates/mempool_infra/src/component_client.rs, crates/mempool_infra/src/component_server.rs, crates/mempool_infra/src/component_server_client_test.rs
**Stack**:
- #185
- #167
- #166
- #161
- #160
- #198 ⬅
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/198)
=> refactor: rename component infra to requests and handlers

Cargo.lock, crates/mempool_infra/Cargo.toml, crates/mempool_infra/build.rs, crates/mempool_infra/proto/component_a_service.proto, crates/mempool_infra/proto/component_b_service.proto, crates/mempool_infra/src/component_server_client_rpc_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/202)
=> build: add proto files and build them

Cargo.lock, crates/mempool/Cargo.toml, crates/mempool/src/mempool.rs, crates/mempool_types/Cargo.toml, crates/mempool_types/src/mempool_types.rs
**Stack**:
- #167
- #166
- #161
- #160 ⬅
=> feat: wrap mempool as a component with trait, client and server

crates/gateway/src/stateless_transaction_validator_test.rs, crates/mempool/src/mempool_test.rs, crates/mempool_node/src/config/config_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/203)
=> test: use assert matches for more informative error message

config/default_config.json, crates/gateway/src/config.rs, crates/gateway/src/gateway.rs, crates/gateway/src/gateway_test.rs, crates/gateway/src/starknet_api_test_utils.rs, crates/gateway/src/stateful_transaction_validator_test.rs, crates/gateway/tests/end_to_end_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/206)
=> style: change "transaction" to "tx" in variable names

Cargo.lock, Cargo.toml, crates/task_executor/Cargo.toml, crates/task_executor/src/tokio_executor.rs, crates/task_executor/src/tokio_executor_test.rs
commit-id:19e51778
---
**Stack**:
- #174
- #173
- #172
- #51 ⬅
=> chore: add simple tokio executor tests

Cargo.lock, commitlint.config.js, crates/gateway/Cargo.toml, crates/tests-integration/Cargo.toml, crates/tests-integration/src/integration_test_utils.rs
Use reqwest built-in status code checker.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/204)
=> refactor(tests-integration): http request checks

Cargo.lock, crates/gateway/Cargo.toml, crates/gateway/src/errors.rs, crates/gateway/src/gateway.rs, crates/tests-integration/tests/end_to_end_test.rs
commit-id:9cd8bcdd
---
**Stack**:
- #174
- #173 ⬅
=> chore: add error to gateway runner and rename

crates/gateway/src/gateway.rs, crates/gateway/src/gateway_test.rs, crates/mempool_types/src/mempool_types.rs, crates/tests-integration/tests/end_to_end_test.rs
commit-id:4e4367d7
---
**Stack**:
- #167
- #166
- #161 ⬅
=> feat: replace network-component to trait-based communication

Cargo.lock, crates/gateway/Cargo.toml, crates/gateway/src/gateway_test.rs, crates/mempool/Cargo.toml, crates/mempool/src/mempool.rs, crates/mempool/src/mempool_test.rs, crates/mempool_types/Cargo.toml, crates/mempool_types/src/mempool_types.rs, crates/tests-integration/tests/end_to_end_test.rs
commit-id:4e0d8a62
---
**Stack**:
- #167 ⬅
- #166
=> feat: remove deprecated network component from gateway and batcher

Cargo.lock, crates/mempool/Cargo.toml, crates/mempool/src/mempool.rs, crates/mempool_infra/Cargo.toml, crates/mempool_node/Cargo.toml, crates/mempool_node/src/bin/dump_config.rs, crates/mempool_types/Cargo.toml, crates/mempool_types/src/mempool_types.rs, crates/tests-integration/Cargo.toml
=> build: rename package names to include starknet_ prefix

crates/mempool/src/mempool.rs, crates/mempool_infra/src/component_client.rs, crates/mempool_infra/src/component_definitions.rs, crates/mempool_infra/src/component_server.rs, crates/mempool_infra/src/component_server_client_test.rs, crates/mempool_infra/src/lib.rs, crates/mempool_infra/tests/common/mod.rs, crates/mempool_infra/tests/component_server_client_test.rs, crates/mempool_types/src/mempool_types.rs
commit-id:16da86a2
---
**Stack**:
- #216 ⬅
- #215
- #214
- #213
=> chore: cleanup and extend todo comments

crates/mempool_infra/tests/common/mod.rs, crates/mempool_infra/tests/component_server_client_test.rs
commit-id:68fd1fa2
---
**Stack**:
- #228 ⬅
- #227
=> chore: move infra test utils from test to common

crates/gateway/src/gateway_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/230)
=> test: improve error message on test_add_tx

crates/gateway/src/stateless_transaction_validator_test.rs
The previous way the test was organized was a bad design.
The "validate non-zero fee" should not be a part of every other scenario of the tests for stateless tx validator.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/232)
=> test: make the stateless tx validator a more correct unit test

crates/gateway/src/starknet_api_test_utils.rs, crates/gateway/src/stateless_transaction_validator_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/238)
=> test: some cleanup in stateless tx validation test

crates/gateway/src/state_reader_test_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/242)
=> fix: initialize rpc test state for multiple instances

crates/gateway/src/gateway.rs, crates/gateway/src/gateway_test.rs, crates/mempool_types/src/mempool_types.rs, crates/tests-integration/tests/end_to_end_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/237)
=> refactor: add MempoolClient type alias

Cargo.lock, Cargo.toml, crates/gateway/src/gateway.rs, crates/gateway/src/gateway_test.rs, crates/gateway/src/starknet_api_test_utils.rs, crates/gateway/src/stateful_transaction_validator.rs, crates/gateway/src/stateless_transaction_validator.rs, crates/gateway/src/stateless_transaction_validator_test.rs, crates/gateway/src/utils.rs, crates/tests-integration/src/integration_test_setup.rs, crates/tests-integration/src/integration_test_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/241)
=> chore: upgrade sn-api version

Cargo.lock, Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/257)
=> chore: upgrade blockifier version

Cargo.lock, crates/gateway/src/gateway_test.rs, crates/gateway/src/lib.rs, crates/gateway/src/starknet_api_test_utils.rs, crates/gateway/src/state_reader_test_utils.rs, crates/gateway/src/stateful_transaction_validator_test.rs, crates/tests-integration/tests/end_to_end_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/239)
=> test: add deploy_account test to gateway_test and stateful test

Cargo.lock, Cargo.toml, crates/mempool_infra/Cargo.toml, crates/mempool_infra/tests/component_server_client_http_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/263)
=> test: components communication using http with hyper

Cargo.lock, Cargo.toml, crates/gateway/src/rpc_state_reader.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/258)
=> feat: add cairo0 support to rpc_state_reader

crates/mempool/src/lib.rs, crates/mempool/src/mempool.rs, crates/mempool/src/transaction_pool.rs, crates/mempool_types/src/errors.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/200)
=> feat: add transaction store data structure

crates/mempool/src/mempool.rs, crates/mempool/src/transaction_pool.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/264)
=> feat(mempool): update tx pool

crates/gateway/src/gateway_test.rs, crates/gateway/src/state_reader_test_utils.rs, crates/gateway/src/stateful_transaction_validator_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/267)
=> test: add invoke cairo0 to stateful validations and gateway test

crates/mempool/src/mempool_test.rs
Shouldn't be mixed-in with the tests
commit-id:b5919717
---
**Stack**:
- #270
- #269 ⬅
=> refactor: hoist up util

crates/mempool/src/mempool_test.rs
**Stack**:
- #276
- #270 ⬅
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/270)
=> refactor: reduce allocations in tests

crates/mempool/src/mempool.rs, crates/mempool/src/priority_queue.rs, crates/mempool/src/transaction_pool.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/287)
=> refactor(mempool): rename priority queue structs

crates/mempool/src/mempool.rs, crates/mempool/src/priority_queue.rs, crates/mempool/src/transaction_pool.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/286)
=> refactor(mempool): add transaction reference struct

crates/tests-integration/src/state_reader.rs, crates/tests-integration/tests/end_to_end_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/273)
=> test: add cairo0 to integration test

crates/mempool/src/mempool.rs, crates/mempool/src/transaction_pool.rs
push is more for stacks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/293)
=> chore: rename tx pool from push to insert

crates/mempool/src/mempool.rs, crates/mempool/src/priority_queue.rs
push is more for stacks
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/304)
=> chore: rename txs_queue.push

crates/mempool/src/mempool.rs, crates/mempool/src/transaction_pool.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/288)
=> refactor(mempool): add new method for transaction reference struct

crates/mempool/src/mempool.rs
In the TODO, handle_tx means insert_tx
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/306)
=> refactor: use common logic for new/add_tx

crates/mempool/src/mempool.rs, crates/mempool/src/mempool_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/323)
=> refactor(mempool): rename tx_queue

crates/mempool/src/mempool.rs, crates/mempool/src/transaction_queue.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/322)
=> feat(mempool): implement iter method for mempool

crates/mempool/src/transaction_queue.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/325)
=> refactor(mempool): transaction_queue remove from trait

crates/mempool/src/transaction_pool.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/328)
=> fix(mempool): fix transaction reference destructuring

crates/mempool/src/transaction_pool.rs
It's an implementation detail of tx pool
commit-id:5acb39ae
=> fix: make account transaction index private

Cargo.lock, Cargo.toml, crates/gateway/Cargo.toml, crates/gateway/src/gateway.rs, crates/gateway/src/gateway_test.rs, crates/gateway/src/lib.rs, crates/gateway/src/state_reader_test_utils.rs, crates/gateway/src/stateful_transaction_validator_test.rs, crates/gateway/src/stateless_transaction_validator_test.rs, crates/gateway/src/utils.rs, crates/test_utils/Cargo.toml, crates/test_utils/src/lib.rs, crates/test_utils/src/starknet_api_test_utils.rs, crates/tests-integration/Cargo.toml, crates/tests-integration/src/integration_test_utils.rs, crates/tests-integration/src/state_reader.rs, crates/tests-integration/tests/end_to_end_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/329)
=> chore: make starknet_api_test_utils enabled in test mode

crates/mempool/src/mempool_test.rs
Motivation: subsequent PRs will want to use:
```rust
add_tx_input!(tx_hash: ..., address: ...)
```
which was impossible under the previous implementation, due to the macro not being able to differentiate between the above and the `add_tx_input(tip,tx_hash)` variant (the args are untyped).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/341)
=> refactor: make add_tx_input take kwargs

Cargo.lock, crates/gateway/Cargo.toml, crates/gateway/src/communication.rs, crates/gateway/src/gateway.rs, crates/gateway/src/gateway_test.rs, crates/gateway/src/lib.rs, crates/mempool_infra/src/component_server.rs, crates/mempool_infra/tests/component_server_client_test.rs, crates/tests-integration/Cargo.toml, crates/tests-integration/src/integration_test_setup.rs
commit-id:689882a6
---
**Stack**:
- #339
- #311
- #310
- #309 ⬅
=> feat: adding empty server and refactoring ComponentServer

crates/tests-integration/src/integration_test_setup.rs, crates/tests-integration/tests/end_to_end_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/356)
=> fix: remove mut from integration setup get_txs

Cargo.lock, Cargo.toml, crates/gateway/Cargo.toml, crates/gateway/src/compilation.rs, crates/gateway/src/compiler_version.rs, crates/gateway/src/rpc_state_reader.rs, crates/gateway/src/state_reader.rs, crates/gateway/src/state_reader_test_utils.rs, crates/gateway/src/stateful_transaction_validator_test.rs, crates/gateway/src/stateless_transaction_validator.rs, crates/gateway/src/stateless_transaction_validator_test.rs, crates/gateway/src/test_utils.rs, crates/mempool/Cargo.toml, crates/mempool/src/mempool_test.rs, crates/starknet_sierra_compile/Cargo.toml, crates/starknet_sierra_compile/src/utils.rs, crates/test_utils/Cargo.toml, crates/test_utils/src/starknet_api_test_utils.rs, crates/tests-integration/Cargo.toml, crates/tests-integration/src/state_reader.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/360)
=> chore: upgrade blockifier version to v0.8.0-dev.0

crates/mempool/src/mempool.rs, crates/mempool/src/transaction_queue.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/363)
=> refactor: rename pop_last_chunk to pop_chunk

crates/mempool_infra/src/component_client.rs, crates/mempool_infra/tests/component_server_client_http_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/361)
=> test: add a dedicated test to component client http

crates/tests-integration/src/integration_test_utils.rs, crates/tests-integration/src/state_reader.rs
=> refactor: separate creation of the test state reader factory

crates/mempool/src/mempool_test.rs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/366)
=> refactor: test_get_txs to dynamically determine max requested txs

crates/gateway/src/communication.rs, crates/mempool/src/communication.rs, crates/mempool_node/src/lib.rs, crates/mempool_node/src/servers.rs
commit-id:0f64f96b
---
**Stack**:
- #339
- #311
- #355
- #310 ⬅
=> feat: add functionality to create all servers

crates/tests-integration/src/integration_test_setup.rs, crates/tests-integration/src/state_reader.rs, crates/tests-integration/tests/end_to_end_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/371)
=> refactor: rename n_accounts in integration tests

crates/mempool/src/mempool_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/374)
=> feat: remove add_tx test boilerplate

crates/mempool_infra/src/component_runner.rs, crates/mempool_infra/src/component_runner_test.rs
=> chore: delete component creator trait

crates/tests-integration/src/integration_test_setup.rs, crates/tests-integration/src/state_reader.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/372)
=> fix: change n_accounts to usize

crates/mempool/src/mempool_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/389)
=> refactor(mempool): use iter method in check-mempool-txs-eq function

crates/mempool/src/mempool.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/386)
=> refactor(mempool): update method signature

crates/mempool/src/mempool_test.rs
Currently unused, will soon be added to add_tx tests in order to
differentiate between the tx nonce and the account nonce.
Note: Previously, the account nonce was hard-coded to 0 through the
default() constructor of Account.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/388)
=> feat: add account_nonce to mempool test

crates/mempool_infra/src/component_definitions.rs, crates/mempool_infra/tests/component_server_client_http_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/400)
=> test: add faulty server tests

crates/mempool_infra/src/component_definitions.rs, crates/mempool_node/src/communication.rs, crates/mempool_node/src/main.rs, crates/mempool_node/src/servers.rs, crates/tests-integration/src/integration_test_setup.rs
=> fix: change to_owned() to take() for ComponentCommunication

crates/mempool_infra/tests/component_server_client_http_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/417)
=> chore: reorder the test functions to satisfy conventions

crates/tests-integration/src/state_reader.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/422)
=> refactor: remove cairo_version(), it's pub now

crates/mempool_infra/tests/common/mod.rs, crates/mempool_infra/tests/component_server_client_http_test.rs, crates/mempool_infra/tests/component_server_client_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/418)
=> chore: move test components' enums to common

crates/mempool/src/transaction_queue.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/410)
=> refactor(mempool): change address-to-tx value type to TransactionReference

config/default_config.json, crates/gateway/src/config.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/405)
=> chore: align default config with python gateway

crates/mempool_test_utils/src/starknet_api_test_utils.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/434)
=> chore: remove deployer_address from deploy_tx_args

Cargo.lock, crates/mempool_infra/Cargo.toml, crates/mempool_infra/tests/component_server_client_http_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/435)
=> test: add use of restest crate to reduce boilerplate

crates/mempool/src/transaction_queue.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/433)
=> refactor(mempool): refactor get_nonce method for transaction queue

crates/mempool_test_utils/src/starknet_api_test_utils.rs
=> chore: remove ignore flag from doc test

crates/tests-integration/src/state_reader.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/436)
=> chore: remove todos

crates/mempool_test_utils/src/starknet_api_test_utils.rs
Also use it in trivial deploy_tx constructor
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/457)
=> feat: add deploy account to tx generator

crates/gateway/src/errors.rs, crates/gateway/src/stateless_transaction_validator.rs, crates/gateway/src/stateless_transaction_validator_test.rs
After checking with Ilya, the entry points need to be sorted
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/373)
=> feat(gateway): validate that entry points are sorted by selector

crates/mempool_test_utils/src/starknet_api_test_utils.rs
Simplify usage.
commit-id:1b334549
=> refactor: refactor AccountTransactionGenerator

Cargo.lock, Cargo.toml, crates/gateway/Cargo.toml, crates/gateway/src/gateway_test.rs, crates/mempool_types/Cargo.toml, crates/mempool_types/src/communication.rs, crates/mempool_types/src/mempool_types.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/385)
=> test(gateway): use mock mempool client

crates/mempool/src/mempool_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/463)
=> test(mempool): rename get_txs test variables

crates/mempool/src/mempool_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/467)
=> test(mempool): remove comments in add_tx_input macro

crates/mempool/src/mempool_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/475)
=> test(mempool): test get_txs with holes, multiple accounts

crates/gateway/Cargo.toml, crates/mempool_test_utils/Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/484)
=> chore: add blockifier feature testing to main toml

crates/mempool/src/mempool_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/441)
=> test(mempool): add sequential nonces txs

crates/mempool/src/mempool_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/474)
=> test(mempool): test get_txs with holes, single account

crates/mempool/src/mempool_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/480)
=> test(mempool): flow test with holes

crates/mempool_test_utils/src/starknet_api_test_utils.rs
The tx generator was identifying the contract instance id with the number of _total_ accounts in the system, which was incorrect, since instance_id in a `FeatureContract` is the the index of the contract without the sequence of all contracts _of the same type_ created in the system.
This fix retains the original meaning of `AccountId` for better UX, so they can refer to accounts by their index given in the constructor, but adds an internal mapping between this id and the "correct" instance_id that FeatureContract expects.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/459)
=> fix: fix tx generator instance ids

crates/mempool/src/mempool_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/442)
=> test(mempool): refactor test_add_tx to use mempool state

crates/mempool/src/mempool_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/481)
=> test(mempool): get_txs multi nonce

crates/mempool_infra/tests/component_server_client_http_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/501)
=> test: validate server response from a faulty client

crates/mempool_infra/src/component_server.rs, crates/mempool_infra/tests/component_server_client_http_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/514)
=> chore: make ComponentServerHttp use the ComponentServerStarter trait

crates/mempool/Cargo.toml, crates/mempool/src/mempool.rs, crates/mempool_types/src/errors.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/509)
=> fix(mempool): fix nonce incremental

crates/gateway/src/errors.rs, crates/gateway/src/stateful_transaction_validator.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/513)
=> refactor(gateway): remove unnecessary error

crates/gateway/src/communication.rs, crates/mempool/src/communication.rs, crates/mempool_infra/src/component_server/definitions.rs, crates/mempool_infra/src/component_server/empty_component_server.rs, crates/mempool_infra/src/component_server/local_component_server.rs, crates/mempool_infra/src/component_server/mod.rs, crates/mempool_infra/src/component_server/remote_component_server.rs, crates/mempool_infra/tests/component_server_client_http_test.rs, crates/mempool_infra/tests/component_server_client_test.rs, crates/mempool_node/src/servers.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/523)
=> refactor: sort component servers into dedicated files

crates/mempool/src/mempool_test.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/489)
=> test(mempool): add commit block test that exclude some txs
