starkware-libs/mempool

scripts/clippy.sh
scripts/rust_fmt.sh

**Stack**:
- #11
- #10
- #9 ⬅
- #8
- #7
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/9)

fix: add rustfmt/clippy scripts to make CI pass

---

.github/workflows/ci.yml

- merge_group isn't relevant
- no python tests here
- not sure why we need all-tests
---
**Stack**:
- #11
- #10 ⬅
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/10)

fix: ci.yml remove unused stuff

---

Cargo.toml
crates/gateway/Cargo.toml
crates/gateway/src/errors.rs
crates/gateway/src/gateway.rs
crates/gateway/src/gateway_test.rs
crates/gateway/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/3)

Implement API Gateway skeleton and unit tests

---

Cargo.toml
crates/gateway/Cargo.toml
crates/gateway/src/gateway.rs
crates/gateway/src/gateway_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/17)

refactor: use axum instead of hyper

---

Cargo.toml
crates/gateway/Cargo.toml
crates/gateway/src/gateway_test.rs

refactor test:
- dont need to pass through BufReader
- extract cast to bytes into test util
- cast string lossy to save unwrap
- spacing
- use better str compare
chore:
- `hyper` version is way too old, bump it.
- add `pretty_assertions` for nicer diff.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/26)

refactor: simplify test

---

Cargo.toml
crates/gateway/Cargo.toml
crates/gateway/src/config_test.rs
crates/gateway/src/gateway.rs
crates/gateway/src/json_files_for_testing/gateway_config.json
crates/gateway/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/23)

feat: add config with papyrus_config

---

Cargo.lock
crates/gateway/src/errors.rs
crates/gateway/src/gateway.rs

- use more concise types for ip/port to make cast to IP (and config creation in general) error-free.
- extract routes to dedicated function: this practice and naming as `app` a known idiom: this makes for easier testing later on, and also will contain other configurations later on like banned IPs.
- Fix naming of arg in `add_transaction`: the arg is already deserialized from json, so no _json suffix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/27)

refactor: simplify and reorganize Gateway

---

Cargo.lock
Cargo.toml
crates/gateway/Cargo.toml
crates/gateway/tests/routing_test.rs

- tests that routes behave the way we expect, shouldn't have too much logic here, just test status codes and return values. Proper integration/flow tests will be in their own testing file.
- add `tower` dependency that `axum` uses in order to simulate an HTTP request via the `oneshot` call: this simulates the HTTP request without having to spin up an actual server and perform IO.
- Currently add_transaction test is identical to the one in gateway_test.rs, but they'll diverge once real logic kicks in. At that point the routes test will only test for success codes in basic scenarios.
- is_alive is currently just a dummy test, since it isn't implemented yet.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

feat: add routes test (semi-integration test)

---

Cargo.toml
crates/gateway/src/errors.rs
crates/gateway/src/starknet_api_test_utils.rs
crates/gateway/src/transaction_validator.rs
crates/gateway/src/transaction_validator_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/29)

feat: stateless validator add non zero fee check

---

crates/gateway/tests/routing_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/39)

test: use fixed path in tests

---

crates/gateway/src/starknet_api_test_utils.rs
crates/gateway/src/stateless_transaction_validator.rs
crates/gateway/src/stateless_transaction_validator_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/45)

test: generalize resource bounds related tests

---

crates/gateway/src/errors.rs
crates/gateway/src/starknet_api_test_utils.rs
crates/gateway/src/stateless_transaction_validator.rs
crates/gateway/src/stateless_transaction_validator_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/38)

feat: stateless validator add calldata len validator

---

crates/gateway/src/errors.rs
crates/gateway/src/stateless_transaction_validator.rs
crates/gateway/src/stateless_transaction_validator_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/54)

chore: rename fee related fields to resource bounds

---

crates/gateway/src/errors.rs
crates/gateway/src/starknet_api_test_utils.rs
crates/gateway/src/stateless_transaction_validator.rs
crates/gateway/src/stateless_transaction_validator_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/59)

chore: some renaming

---

Cargo.lock
Cargo.toml
crates/mempool/Cargo.toml
crates/mempool/src/lib.rs
crates/mempool/src/priority_queue.rs
crates/mempool/src/priority_queue_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/34)

feat(mempool): implement priority queue data structure

---

crates/mempool/src/priority_queue.rs

Implements From function for PriorityQueue.
gets a vector of InternalTransactions and adds them to a PriorityQueue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/57)

feat: implement from for priority queue

---

Cargo.lock
crates/mempool/Cargo.toml
crates/mempool/src/errors.rs
crates/mempool/src/lib.rs
crates/mempool/src/mempool.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/43)

feat: add Mempool and its API

---

.github/workflows/ci.yml

- instead of compiling from source, use a cached `cargo install` github action (which appears to be cached by default!), and then run udeps from cargo.
- this is the recommended installation method from udeps' readme.
- motivation: Previous method of installation seemed to hit compilation errors [here] (https://reviewable.io/reviews/starkware-libs/mempool/42#-), that weren't reproducible when running through `cargo udeps`.
- NOTE: The github action used for cargo-install only has ~100 stars, which isn't a lot, but I found a few well-used projects that use them, like tokio-rs/prost and wez/wezterm, so it's probably OK.
- ALTERNATIVE: switching from udeps to [machete](https://github.com/bnjbvr/cargo-machete). The cairo team did and they're pleased with the results.
- - -
This change …

fix: install cargo udeps differently

---

Cargo.lock
Cargo.toml
crates/gateway/Cargo.toml
crates/gateway/src/gateway.rs
crates/gateway/tests/end_to_end_test.rs
crates/mempool/src/mempool.rs
crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/106)

test: implement end to end test

---

Cargo.lock
Cargo.toml
crates/task_executor/Cargo.toml
crates/task_executor/src/executor.rs
crates/task_executor/src/lib.rs

Proper usage example via tokio in upcoming PR, here is an abstract one:
```rust
async fn initiates_a_cpu_bound_task() -> Result<(), Box<dyn std::error::Error>>{
let executor = SomethingThatImplementsTaskExecutor::new();
let derp = "DERP".to_string();
let res = executor.spawn_blocking(move || {
// Simulate blocking cpu computation
let derp_world += derp + " world"
// return the result of the computation
derp_world
}).await?;
assert_eq!(res.as_str(), "DERP world");
Ok(())
}
```
```rust
async fn initiates_an_io_bound_task() -> Result<(), Box<dyn std::error::Error>>{
let executor = SomethingThatImplementsTaskExecutor::new();
let derp = "DERP";
let res = executor.spawn(async move || {
tokio::time::sleep(tokio::time::Duration::from_secs(1)).await; // async sleep.
println!("{derp}");
derp …
```

feat: add task executor trait

---

config/default_config.json
crates/mempool_node/src/config/config_test.rs
crates/mempool_node/src/config/mod.rs
crates/mempool_node/src/test_files/mempool_node_config.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/171)

feat: add rpc state reader config to mempool node config

---

crates/gateway/src/errors.rs
crates/gateway/src/gateway_client.rs
crates/gateway/src/gateway_test.rs
crates/gateway/src/starknet_api_test_utils.rs
crates/gateway/tests/end_to_end_test.rs
crates/gateway/tests/routing_test.rs

- Remove errors originating solely from the util: they should not be
part of the API. In fact, all of this code should not be part of
production, however this will be dealt with in an upcoming refactor
that create a dedicated integration tests crate.
- Use reqwest instead of hyper --- it is a more high-level library, so
less boilerplate.
- Split up `add_tx` into three operations, sending, asserting status
code, and asserting expected value. The DuplicateTransaction use-case
will be added soon, and will require asserting for a different
status-code. The assertion was added to reduce boilerplate in the
test.
- Note: no need to pass through utf-8, since Bytes<String> supports comparison
with &str.
commit-id:bb48f1f2
---
**Stack**:
- #177 ⬅
- #176
⚠️ *Part of a stack created by …

refactor: gateway-client

---

Cargo.lock
Cargo.toml
crates/task_executor/Cargo.toml
crates/task_executor/src/lib.rs
crates/task_executor/src/tokio_executor.rs

- Add a naive task executor, currently utilizing tokio for both CPU and IO
tasks.
- Tokio promises two separate threadpools for spawn_blocking and spawn,
which should prevent starvation, but not sure how this affects
latency.
- `spawn_with_handle` is needed because of the generality of
`TaskExecutor` trait and since rust doesn't have
reflection/downcasting: tokio's spawn return value is `JoinHandle`,
which implements `Future`, but one cannot get a JoinHandle from a
`impl Future` typed object, hence a separate method is needed.
- More tests coming up.
TODO: when we start managing tokio runtimes explicitly, we might
have to modify the executor to be aware of the runtime.
TODO 2: if we need to throttle cpu-bound tasks, see semaphore
implementation of this commit on the branch …

feat: add tokio executor

---

crates/gateway/src/gateway.rs
crates/gateway/src/gateway_client.rs
crates/gateway/src/gateway_test.rs
crates/gateway/tests/end_to_end_test.rs

- Added a test for the tx_hash inside test_add_tx in the gateway_test, by computing it separately.
- Remove `expected` check in e2e test[_utils], checking the tx_hash is covered now by the gateway_test, also the e2e test will have different expected value to check very soon --- it'll compare external_txs with the thin/internal txs output from the mempool.
- Note: `assert_add_tx_success` might be no longer necessary, will refactor separately.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/194)

chore: return TransactionHash from GW add_tx

---

Cargo.lock
crates/mempool/Cargo.toml
crates/mempool/src/mempool_test.rs

- move: `create_for_testing` to the bottom, no logic changes.
- feat: add a simple macro for generating mempool input.
- feat: add util for testing mempool txs, in ascending order, without having to call get_txs (for use in non-`get_tx` unit tests).
- chore: make existing tests use the above utils, no logic changes.
- chore: add a stability check to the dup-check test; make sure the mempool retains the original tx when the dup is attempted.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/199)

refactor: mempool test setup

---

Cargo.lock
Cargo.toml
crates/gateway/Cargo.toml
crates/gateway/src/lib.rs
crates/tests-integration/Cargo.toml
crates/tests-integration/src/integration_test_utils.rs
crates/tests-integration/src/lib.rs
crates/tests-integration/tests/end_to_end_test.rs

- move e2e test into crate
- rename gateway client into a test utils module in the crate + remove
stale typedef.
commit-id:8948e34d
---
**Stack**:
- #174
- #173
- #172 ⬅

chore: create integration tests crate

---

crates/mempool/src/mempool_test.rs
crates/mempool/src/priority_queue.rs

`BtreeSet` expects keys to be unique, so if we only cmp based on tip,
trying to add txs with identical tips fails silently on the `push` that
is now asserted against.
Note: we'll probably add better tie breakers before resorting to hash cmp, but still it's a good fallback to have.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/189)

fix: add tie-breaker to mempool ordering

---

crates/mempool/src/priority_queue.rs

add address priority queue. Will be used in Mempool, multiple txs per account
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/210)

feat: add address priority queue

---

crates/mempool_infra/src/component_client.rs
crates/mempool_types/src/mempool_types.rs

**Stack**:
- #224
- #223 ⬅
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/223)

chore: move ClientError definition to component client module

---

Cargo.lock
Cargo.toml
crates/mempool/Cargo.toml
crates/mempool/src/mempool.rs
crates/mempool/src/mempool_test.rs

bugs:
- missing assertion...
- use `zip_eq`, which panics if lengths have different length.
refactor:
- add track_caller, to make failures point to the test error location, rather than the test_util itself.
- alphabetize.
- variable naming.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/205)

fix: make check_mempool_txs_eq work

---

crates/gateway/src/config.rs
crates/gateway/src/errors.rs
crates/gateway/src/starknet_api_test_utils.rs
crates/gateway/src/stateless_transaction_validator.rs
crates/gateway/src/stateless_transaction_validator_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/225)

feat: add declare specific size related stateless tx validator

---

Cargo.lock
crates/gateway/src/gateway.rs
crates/mempool_infra/src/component_client.rs
crates/mempool_types/src/errors.rs
crates/tests-integration/Cargo.toml
crates/tests-integration/src/integration_test_setup.rs
crates/tests-integration/src/integration_test_utils.rs
crates/tests-integration/src/lib.rs
crates/tests-integration/tests/end_to_end_test.rs

Most of the changes are extraction from the end-to-end test, with the
following differences:
- spawning tasks via `TokioExecutor#spawn_with_handle`, which the mock
stores as a field to facilitate aborting the job (our `main` will
likely do something similar to this).
- added abstract add/get tx methods, the add uses the GatewayClient
util, and the get currently just a channel (and will use the future
BatcherMock when ready).
- needed to make `config` in `Gateway` public, it doesn't have any
invariants on it anyway so it should have no problem being pub i think.
commit-id:b41211a9

feat: add IntegrationTestSetup

---

crates/mempool/src/priority_queue.rs

- pop_front in Vec is O(n).
- should be private to protect invariant.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/240)

fix: change inner AddressPrioQueue

---

config/default_config.json
crates/gateway/src/config.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/245)

chore: fix description of stateless tx validator config

---

Cargo.lock
crates/tests-integration/Cargo.toml
crates/tests-integration/src/state_reader.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/259)

test: add cairo0 support to initialize_rpc_test_state

---

crates/gateway/src/gateway_test.rs
crates/mempool/src/mempool.rs
crates/mempool/src/mempool_test.rs

And impl via Default
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/271)

refactor: use mempool::empty everywhere

---

crates/tests-integration/src/integration_test_setup.rs
crates/tests-integration/src/integration_test_utils.rs
crates/tests-integration/src/state_reader.rs
crates/tests-integration/tests/end_to_end_test.rs

Currently rpc state reader defaults to a single account contract, this
extends the behavior to create a variable number, to make it easier to
setup integration tests (otherwise every test will have a bunch of
deploy_account expensive boilerplate).
Alternative: increase the default to something sensible, like 6.
This will most likely suffice, but it's a bit of a magic number and
might have unnecessary overhead. That is, while debugging users might
not understand where so many contracts are coming from.
commit-id:4ef4de46
---
**Stack**:
- #253
- #252
- #268 ⬅
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

feat: initialize accounts in integration tests

---

crates/mempool/src/mempool_test.rs
crates/mempool_types/src/errors.rs

Uses pretty_assertions, colored and formatted output.
commit-id:5dc07b7c

feat: use assert_eq for Ok MempoolResult

---

Cargo.lock
Cargo.toml
crates/gateway/Cargo.toml
crates/gateway/src/errors.rs
crates/gateway/src/gateway.rs
crates/starknet_sierra_compile/Cargo.toml
crates/starknet_sierra_compile/src/compile.rs
crates/starknet_sierra_compile/src/lib.rs
crates/starknet_sierra_compile/src/utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/234)

feat: compile sierra to casm in declare tx

---

crates/gateway/src/errors.rs
crates/gateway/src/rpc_objects.rs
crates/gateway/src/rpc_state_reader.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/284)

fix: rpc_state_reader return default for nonce and class_hash

---

crates/mempool/src/mempool_test.rs

- Remove check that txs were inserted after `new` --- this tests `new`, which is out of scope.
- use check_mempool_txs_eq to check mempool contents.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/294)

fix: fix get txs test

---

crates/mempool/src/mempool.rs

`state`, as it's currently implemented, will be soon removed. (We'll add a similar construct soon to track current block state, but it'll be behave differently.)
Therefore, we'll need to rely on the tx_pool's dup check; insertion to the queue does not check for dups, it _assumes_ that dup checks have already occured.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/299)

fix: switch insertion order in add_tx

---

crates/mempool/src/mempool.rs
crates/mempool/src/mempool_test.rs

Duplicates inside the inputs is an input error for the mempool, so should be returned to the user.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/303)

feat: make mempool::new return error

---

crates/mempool/src/mempool.rs
crates/mempool/src/mempool_test.rs

We'll soon add a sort of current_block_state, that will track nonce and
balance in between calls to commit-block, but it will behave to
different from this struct, so it'll be reimplemented from scratch.
Removed a test that tested the panic behavior of inserting into the
state.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/295)

chore: remove state field from mempool

---

crates/mempool/src/communication.rs
crates/mempool/src/mempool.rs
crates/mempool/src/mempool_test.rs
crates/mempool_types/src/mempool_types.rs

Account isn't really used yet, but since it's already being passed alongside tx we might as well add MempoolInput.
Changes in tests are all just passing mempoolInput type into add_transaction, no logic changes
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/305)

feat: use MempoolInput in add_tx

---

crates/mempool/src/transaction_pool.rs

Wasn't needed, and the pool should not be cloned in any user flow.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/321)

fix: remove Clone from TransactionPool

---

crates/mempool/src/transaction_pool.rs

New name better implies this being a transaction index, rather than an
address index.
commit-id:ecb46826
---
**Stack**:
- #320
- #318
- #317
- #316
- #315
- #314 ⬅

refactor: rename address pq

---

crates/mempool/src/transaction_pool.rs

Until we support fee escalation, this should always return None.
Subsequent PRs will use this DS, and panic if `Some` is returned.
commit-id:b0eee880
---
**Stack**:
- #320
- #318
- #317
- #316 ⬅

feat: add AccountTransactionIndex insert

---

crates/mempool/src/mempool.rs
crates/mempool/src/mempool_test.rs
crates/mempool/src/transaction_pool.rs
crates/mempool/src/transaction_queue.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/195)

refactor: update priority queue to use ThinPriorityTransaction

---

crates/gateway/src/errors.rs
crates/gateway/src/gateway.rs
crates/gateway/src/gateway_test.rs
crates/gateway/src/starknet_api_test_utils.rs
crates/gateway/src/stateful_transaction_validator_test.rs
crates/test_utils/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/246)

feat: check that the compiled class hash matches the supplied class

---

Cargo.lock
crates/gateway/src/gateway.rs
crates/mempool_infra/src/component_runner.rs
crates/mempool_infra/src/component_runner_test.rs
crates/mempool_node/Cargo.toml
crates/mempool_node/src/communication.rs
crates/mempool_node/src/components.rs
crates/mempool_node/src/lib.rs

commit-id:6ec10946
---
**Stack**:
- #311
- #310
- #309
- #308 ⬅
- #307
- #262
- #261

fix: change ComponentRunner start param to '&mut self'

---

Cargo.lock
Cargo.toml
crates/gateway/Cargo.toml
crates/gateway/src/starknet_api_test_utils.rs
crates/gateway/src/state_reader_test_utils.rs
crates/tests-integration/Cargo.toml
crates/tests-integration/src/state_reader.rs
crates/tests-integration/tests/end_to_end_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/302)

test: add deploy_account to integration test

---

crates/gateway/src/errors.rs
crates/gateway/src/gateway.rs
crates/gateway/src/gateway_test.rs
crates/starknet_sierra_compile/src/compile.rs
crates/starknet_sierra_compile/src/errors.rs
crates/starknet_sierra_compile/src/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/333)

chore: move compilation errors to dedicated file

---

crates/mempool_infra/src/component_client.rs
crates/mempool_infra/src/component_definitions.rs
crates/mempool_infra/tests/component_server_client_http_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/334)

feat: make generic component client http

---

crates/mempool_infra/src/component_server.rs
crates/mempool_infra/tests/component_server_client_http_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/337)

feat: make generic component server http

---

Cargo.lock
Cargo.toml
crates/gateway/Cargo.toml
crates/gateway/src/rpc_state_reader.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/335)

chore: delete CompileContractClass object

---

crates/mempool/src/mempool_test.rs

also rename subsequent test to be consistent
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/324)

chore: add dup-test for new

---

crates/mempool/src/mempool.rs

Subsequent PRs will add the nonce check.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/346)

fix: dont clone tx in insert_tx

---

crates/gateway/src/compilation.rs
crates/gateway/src/compilation_test.rs
crates/gateway/src/errors.rs
crates/gateway/src/gateway.rs
crates/gateway/src/gateway_test.rs
crates/gateway/src/lib.rs
crates/gateway/src/stateful_transaction_validator_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/344)

chore: code to compilation file from gateway

---

crates/tests-integration/src/integration_test_setup.rs
crates/tests-integration/src/lib.rs
crates/tests-integration/src/mock_batcher.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/332)

feat: add mock batcher and implement as a wrapper in integration test

---

crates/tests-integration/src/integration_test_utils.rs
crates/tests-integration/src/state_reader.rs

In order to add additional integration tests, the Web and RPC servers
must run on unique addresses, otherwise trying to create an additional
server will fail due to the socket already being in use.
This is achieved by selecting the port dynamically, through setting the
port as 0 (dynamic port), which `local_addr` then resolves into an
the actual port selected, that is, replacing `127.0.0.1:0` with
`127.0.0.1:<available_port_that_was_bound_by_TcpListener>`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/357)

fix: support parallel servers in tests

---

crates/mempool_infra/src/component_client.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/377)

refactor: return an error in case response deserialization fails

---

crates/mempool/src/mempool_test.rs
crates/mempool/src/transaction_queue.rs

Update TransactionQueue iter to return reverse order iterator.
- Refactored the `iter` function to return an iterator in reverse order, contrasting with the `BTreeSet` iterator which returns in ascending order.
- This change makes the iteration more intuitive for the mempool queue, which returns transactions by reverse tip order.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/364)

refactor: reverse order iterator for transaction queue

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/365)

feat: request 0 txs from get_txs test

---

Cargo.lock
Cargo.toml
crates/gateway/src/state_reader_test_utils.rs
crates/gateway/src/stateful_transaction_validator.rs
crates/gateway/src/stateful_transaction_validator_test.rs
crates/tests-integration/src/state_reader.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/393)

chore: upgrade papyrus commit to ca83fd42 and blockifier to 0.8.0-dev.1

---

crates/tests-integration/src/integration_test_setup.rs
crates/tests-integration/src/mock_batcher.rs

- Refactored `IntegrationTestSetup` to use the batcher as a service.
- Created `BatcherCommand` for messages sent to the batcher, triggering it to start. Currently, it only prints the connection but will later be used to get messages from the mempool.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/349)

refactor: mock batcher as a service

---

crates/mempool/src/mempool_test.rs

Soon we'll add an `account_nonce` arg, to differentiate between the tx
nonce and the account's nonce during add_tx.
Note: docstring amendment also includes formatting and old Felt code
fix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/387)

refactor: rename nonce in mempool test

---

crates/gateway/src/gateway.rs
crates/gateway/src/stateful_transaction_validator.rs
crates/gateway/src/stateful_transaction_validator_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/381)

refactor(gateway): prepare run_validate for mocking

---

crates/mempool/src/transaction_pool.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/402)

chore: add transaction getter to mempool

---

crates/mempool/src/transaction_queue.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/414)

fix(mempool): remove clone from transaction queue

---

crates/mempool_node/src/main.rs
crates/mempool_node/src/servers.rs

chore: rename and add comments to server-running function

---

crates/gateway/src/lib.rs
crates/gateway/src/utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/404)

chore(gateway): change inner modules to be private

---

config/default_config.json
crates/gateway/src/config.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/406)

chore: align config with python gateway

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/419)

feat(mempool): add from_iter func to TransactionPool

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/413)

feat(mempool): add from_iter func to TransactionQueue

---

crates/mempool/src/transaction_queue.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/382)

refactor(mempool): add error message in transaction queue

---

crates/mempool/src/mempool_test.rs

It was a misnomer, we're asserting the queue, not the entire pool.
commit-id:181fcd98
---
**Stack**:
- #429
- #428
- #427
- #426 ⬅

refactor: rename test util

---

crates/mempool/src/mempool_test.rs

Previous assertion wasn't informative enough on fail.
commit-id:4b2c49c7
---
**Stack**:
- #429
- #428
- #427 ⬅

feat: improve mempool_test debug print

---

crates/mempool/src/transaction_queue.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/412)

feat(mempool): implement remove method for transaction queue

---

crates/mempool_test_utils/src/starknet_api_test_utils.rs

fix: starknet_api_test_utils doc test

---

Cargo.lock
Cargo.toml
crates/gateway/src/gateway.rs
crates/gateway/src/state_reader_test_utils.rs
crates/gateway/src/stateful_transaction_validator.rs
crates/gateway/src/stateful_transaction_validator_test.rs
crates/mempool_test_utils/src/starknet_api_test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/345)

feat: skip validation of an invoke transaction after deploy account

---

crates/mempool_test_utils/src/starknet_api_test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/456)

refactor: rename invoke generator

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/399)

test(mempool): add mempool state struct and new function

---

crates/tests-integration/src/state_reader.rs

`prepare_compiled_contract_classes` should know about stuff it isn't using.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/453)

refactor: simplify state-reader iteration

---

crates/mempool_test_utils/src/starknet_api_test_utils.rs

Moved next to similar constructors `invoke_tx()` and `declare_tx()`.
NOTE: Only move, no internal changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/458)

refactor: move deploy_account_tx next to peers

---

Cargo.lock
Cargo.toml
crates/gateway/Cargo.toml
crates/gateway/src/lib.rs
crates/gateway/src/rpc_objects.rs
crates/gateway/src/rpc_state_reader_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/449)

test(gateway): test RpcStateReader

---

crates/mempool_test_utils/src/starknet_api_test_utils.rs

This sets up the upcoming separation between account ids, which is a UX
artifact for users of the tx generator that represents an index (hence
usize) in the initialization array of accounts; and instance ids, which
is a u16 that is part of an implementation detail of `FeatureContract`s.
More on this in susequent PRs.
commit-id:60101a6e
---
**Stack**:
- #477
- #476 ⬅

refactor: make acocunt id usize

---

Cargo.lock
crates/tests-integration/Cargo.toml
crates/tests-integration/src/integration_test_setup.rs
crates/tests-integration/src/state_reader.rs
crates/tests-integration/tests/end_to_end_test.rs

Make `spawn_test_rpc_state_reader` get an iterator of accounts and have count the number of occurrences by itself, instead of getting specific numbers per account.
To keep the diff small, the map of contract->n_instances_of_contract is cast back to the old type immediately.
Subsequent PRs will remove this cast and make the whole flow use the map.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/454)

feat: add custom accounts to test rpc state reader

---

crates/tests-integration/src/state_reader.rs

This finishes the refactor started at #454, plz view that PR for context.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/455)

refactor: make rpc reader use account map

---

crates/tests-integration/src/integration_test_utils.rs

Due to #454, IntegrationTestSetup now accepts any array of contracts, which are then passed on to the state reader for initialization.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/460)

fix: support custom accounts in constructor

---

crates/mempool_test_utils/src/starknet_api_test_utils.rs
crates/tests-integration/tests/end_to_end_test.rs

- Make e2e use tx generator txs, which track nonces.
- As a result, the test now reflects the way the mempool behaves at the moment, and so only nonce-0 txs are returned from get_txs.
- Once get_txs begin replenishing the queue when the queue gets exhausted, this test should be fixed as per the comment below.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/461)

fix: fix e2e test by using tx generator

---

crates/starknet_sierra_compile/src/test_utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/494)

chore: generalize contract class from file test util

---

crates/mempool_infra/src/component_client.rs
crates/mempool_infra/src/component_server.rs

commit-id:a2509b74
---
**Stack**:
- #222 ⬅
- #220

docs: add documentation for component server

---

crates/mempool/src/transaction_pool.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/443)

feat(mempool): implement remove from nonce for account transaction index

---

crates/gateway/src/compilation.rs
crates/gateway/src/compilation_test.rs
crates/gateway/src/gateway.rs
crates/gateway/src/stateful_transaction_validator_test.rs
crates/mempool_test_utils/src/starknet_api_test_utils.rs
crates/starknet_sierra_compile/src/utils.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/439)

refactor: gateway compiler handle declare tx

---

crates/mempool/src/mempool_test.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starkware-libs/mempool/511)

test(mempool): test_add_tx_fills_nonce_gap
